title: Eggsample Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://example.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Gateway
      category: North Coast
    - name: Backup Gateway
      category: North Coast
    - name: My Old Mutual Mobile App
      description: The web frontend for the application.
      category: Uncategorized
      link: https://example.com/
    - name: Old Mutual Whatsapp Banking
      description: The guts of the application.
      category: Uncategorized
    - name: Oldmutual.co.za
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Old Mutual Mobile App (Rewards)
    - name: Login
      category: Old Mutual Mobile App (Rewards)
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/kong-logomark-blue-256px.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: North Coast
      description: The main servers are located here.
      closed: true
      untitled: true
    - name: Uncategorized
      untitled: true
    - name: Old Mutual Mobile App (Rewards)
      description: The Rewards section of the Old Mutual Banking mobile app
      closed: true
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
